"""remove user history

Revision ID: dceb049abebc
Revises: b61907846d97
Create Date: 2024-05-13 21:59:40.037983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dceb049abebc'
down_revision: Union[str, None] = 'b61907846d97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_hist_gpt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_hist_gpt',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tg_id', sa.VARCHAR(), nullable=False),
    sa.Column('message', sa.VARCHAR(length=128), nullable=False),
    sa.Column('role', sa.VARCHAR(length=9), nullable=False),
    sa.ForeignKeyConstraint(['tg_id'], ['user.tg_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
